### Obtener todos los usuarios
GET http://localhost:3000/users
Content-Type: application/json

###  Obtener un usuario por ID
GET http://localhost:3000/users/1
Content-Type: application/json

### Crear un usuario
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "lauty Arce",
  "email": "lauty@example.com"
}

### Actualizar un usuario
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "name": "lauty Arce",
  "email": "lauty@example.com"
}

### Eliminar un usuario
DELETE http://localhost:3000/users/40
Content-Type: application/json

